### ISSUE TITLE
Example (for config) available? 

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [direktspeed/feathers-couchbase#18]
Good Evening,
thinking to move to couchbase for some data in our POS backend. Your adapter looks very promising.
It would be great if you could provide a sample app or at leaste the couchbaseConfig format.
That would help as we are not yet so familiar with cb. We have the CB server and sync-gateway running on an DO machine and also the couchbase-lite in an droid app.
This would be the missing part :)
Thanks in advance and Greets from Manila
Ralph

**Comment by frank-dspeed** [comment]
@thanks for your interrest i have it already in use and will add documentation here and then ping you again

**Comment by ralph-fuechtenkort** [comment]
Thanks for your reply, try to make it work but thats hard without any example regarding the required imports and configuration. What i tried:

const FeathersCouchbase = require('feathers-couchbase')
var apiConfig = require("../../api-config.json");
var db;

module.exports = function () {
	const app = this;
	var CouchbaseConnection;
	//const Model = createModel(app);
	const paginate = app.get('paginate');
	debugger;
	const Model = {
		couchbaseClient: FeathersCouchbase,
		couchbaseCluster:"http://user:password@localhost:4985",
		couchbaseBucket:"esaas0000",
		paginate:paginate
	   }
	app.set(CouchbaseConnection, FeathersCouchbase(Model));

but that does not work. I think i am missing something.
Can you please give a hint or an example xxx-service.js

thanks and Greets again
Ralph

**Comment by frank-dspeed** [comment]
@ralph-fuechtenkort 
couchbaseClient should be a object holding {
 cluster, bucket, couchbase
}

will release new version sooin that makes that clear

**Comment by frank-dspeed** [comment]
@ralph-fuechtenkort i will close this if you still have questions you can comment here or reopen if you think that the current documentation is not enough for you i also suggest that you look into https://github.com/direktspeed/feathers-couchbase-odm that is using this package and offers you some nice extra stuff like defining a _id _type property and the key gets _id|_type that allows you nice fast coding and direct key lookup without querys.
